version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: curl -L "$TESTS_URL" -o tests.tar
      - run: tar -xvzf tests.tar -C test/Cecs475.BoardGames.Chess.Test
      - run: dotnet restore
      - run: dotnet build
      - run:
          command: |
            if [ -f GRADEME.txt ]; then
                printf "$CIRCLE_USERNAME\n----------------------\n\n" > TESTOUTPUT
                dotnet test test/Cecs475.BoardGames.Chess.Test | tee -a TESTOUTPUT
            fi
      - run:
          when: always
          command: |
            if [ -f GRADEME.txt ]; then
                curl -X POST -H "Content-Type: text/plain" -d @TESTOUTPUT $EMAIL_URL
            fi
      